#!/bin/bash
export MY_KEYSTORE_FILE="/home/ilan/dev/key/spirit2_free_key"
export MY_KEYSTORE_PASS="password"
export MY_KEY_NAME="ilanreidis_key"
export WS="/home/supox/Desktop/nu3001/source_code"
export PROJ="spirit2_free"
cd $WS/$PROJ

rm -rf obj  # obj/local/armeabi/*
rm -rf libs # libs/armeabi/

mkdir libs

/opt/adt-bundle-linux-x86_64-20140321/sdk/tools/android update project --target android-21 --path . --name $PROJ

#mkdir -p res/raw
#cp ../raw/spirit_sh ../$PROJ/res/raw/
#cp ../raw/b1_bin    ../$PROJ/res/raw/
#cp ../raw/b2_bin    ../$PROJ/res/raw/

echo ndk-build start
time /opt/android-ndk-r10d/ndk-build # 2>&1 |grep -i error

mv libs/armeabi/s2d libs/armeabi/libs2d.so
#mv libs/armeabi/ssd libs/armeabi/libssd.so

ant -q clean release

jarsigner -storepass $MY_KEYSTORE_PASS -sigalg MD5withRSA -digestalg SHA1 -keystore $MY_KEYSTORE_FILE -signedjar bin/$PROJ-release-unaligned.apk bin/$PROJ-release-unsigned.apk $MY_KEY_NAME
zipalign -f 4 bin/$PROJ-release-unaligned.apk bin/$PROJ-release.apk

#adb install -r bin/$PROJ-release.apk
